---
- name: Install Nginx
  become: true
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: true

- name: Remove default Nginx site
  become: true
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: Restart Nginx