---
django_repo: "https://github.com/kaaalim/django-sample-app.git"
django_app_dir: /opt/django-app
django_user: django
django_group: django
django_venv: /opt/django-app/venv
django_port: 8000

django_db_name: django_db
django_db_user: django_user
django_db_password: "{{ postgres_password }}"
django_db_port: 5432